export const firstPre = [
  { female: "Akor", male: "Alak", meaning: "Beloved, best, first" },
  { female: "Alaun", male: "Alton", meaning: "Lightning, powerful" },
  { female: "Aly", male: "Kel", meaning: "Legendary, singing, song" },
  { female: "Ang", male: "Adin", meaning: "Beast, monstrous, savage" },
  { female: "Ardul", male: "Amal", meaning: "Blessed, divine, godly" },
  { female: "Aun", male: "Ant", meaning: "Crypt, dead, deadly, death" },
  { female: "Bae", male: "Bar", meaning: "Fate, fated, luck, lucky" },
  { female: "Bal", male: "Bel", meaning: "Burned, burning, fire, flame" },
  { female: "Belar", male: "Bruh", meaning: "Arrow, lance, pierced" },
  { female: "Briz", male: "Berg", meaning: "Graceful, fluid, water, wet" },
  { female: "Bur", male: "Bhin", meaning: "Craft, crafty, sly" },
  { female: "Chal", male: "Chasz", meaning: "Earth, stable" },
  { female: "Char", male: "Kron", meaning: "Sick, venom, venomed" },
  { female: "Chess", male: "Cal", meaning: "Noble, lady/lord" },
  { female: "Dhaun", male: "", meaning: "Infested, plague" },
  { female: "Dil", male: "Dur", meaning: "Cold, ice, still" },
  { female: "Dirz", male: "Div", meaning: "Dream, dreaming, fantasy" },
  { female: "Dris", male: "Riz", meaning: "Ash, dawn, east, eastern" },
  { female: "Eclav", male: "Elk", meaning: "Chaos, mad, madness" },
  { female: "Elvan", male: "Kalan", meaning: "Elf, elven, far, lost" },
  { female: "Elv", male: "Elaug", meaning: "Drow, mage, power" },
  { female: "Erel", male: "Rhyl", meaning: "Eye, moon, spy" },
  { female: "Ethe", male: "Erth", meaning: "Mithril, resolute" },
  { female: "Faer", male: "Selds", meaning: "Oath, sworn, vow" },
  { female: "Felyn", male: "Fil", meaning: "Pale, thin, weak, white" },
  { female: "Filf", male: "Phar", meaning: "Dwarf, dwarven, treacherous" },
  { female: "Gauss", male: "Orgoll", meaning: "Dread, fear, feared, vile" },
  { female: "G'eld", male: "", meaning: "Friend, spider" },
  { female: "Ghuan", male: "", meaning: "Accursed, curse, unlucky" },
  { female: "Gin", male: "Din", meaning: "Berserk, berserker, orc, wild" },
  { female: "Grey", male: "Gul", meaning: "Ghost, pale, unliving" },
  { female: "Hael", male: "Hatch", meaning: "Marked, trail, way" },
  { female: "Hal", male: "Sol", meaning: "Deft, nimble, spider" },
  { female: "Houn", male: "Rik", meaning: "Magic, ring, staff" },
  { female: "Iiv", male: "Dip", meaning: "Liege, war, warrior" },
  { female: "Iim", male: "", meaning: "Life, living, spirit, soul" },
  { female: "Illiam", male: "Im", meaning: "Devoted, heart, love" },
  { female: "In", male: "Sorn", meaning: "Enchanted, spell" },
  { female: "Ilph", male: "", meaning: "Emerald, green, lush, tree" },
  { female: "Irae", male: "Ilzt", meaning: "Arcane, mystic, wizard" },
  { female: "In", male: "Izz", meaning: "Hidden, mask, masked" },
  { female: "Iym", male: "Ist", meaning: "Endless, immortal" },
  { female: "Jan", male: "Duag", meaning: "Shield, warded" },
  { female: "Jhael", male: "Gel", meaning: "Ambitious, clan, kin, family" },
  { female: "Jhul", male: "Jar", meaning: "Charmed, rune, symbol" },
  { female: "Jys", male: "Driz", meaning: "Hard, steel, unyielding" },
  { female: "Lael", male: "Llt", meaning: "Iron, west, western" },
  { female: "Lar", male: "Les", meaning: "Binding, bound, law, lawful" },
  { female: "LiNeer", male: "Mourn", meaning: "Legend, legendary, mythical" },
  { female: "Lird", male: "Ryld", meaning: "Brand, branded, owned, slave" },
  { female: "Lua", male: "Lyme", meaning: "Bright, crystal, light" },
  { female: "Mal", male: "Malag", meaning: "Mystery, secret" },
  { female: "May", male: "Mas", meaning: "Beautiful, beauty, silver" },
  { female: "Micar", male: "", meaning: "Lost, poison, widow" },
  { female: "Min", male: "Ran", meaning: "Lesser, minor, second" },
  { female: "Mol", male: "Go", meaning: "Blue, storm, thunder, wind" },
  { female: "Myr", male: "Nym", meaning: "Lost, skeleton, skull" },
  { female: "Nath", male: "Mer", meaning: "Doom, doomed, fate" },
  { female: "Ned", male: "Nad", meaning: "Cunning, genius, mind, thought" },
  { female: "Nhil", male: "Nal", meaning: "Fear, horrible, horror, outraged" },
  { female: "Neer", male: "", meaning: "Core, root, strong" },
  { female: "Null", male: "Nil", meaning: "Sad, tear, weeping" },
  { female: "Olor", male: "Omar", meaning: "Skin, tattoo, tattooed" },
  { female: "Pellan", male: "Relon", meaning: "North, platinum, wind" },
  { female: "Phaer", male: "Vorn", meaning: "Honor, honored" },
  { female: "Phyr", male: "Phyx", meaning: "Bless, blessed, blessing" },
  { female: "Qualn", male: "Quil", meaning: "Mighty, ocean, sea" },
  { female: "Quar", male: "", meaning: "Aged, eternal, time" },
  { female: "Quav", male: "Quev", meaning: "Charmed, docile, friend" },
  { female: "Qil", male: "Quil", meaning: "Foe, goblin, slave" },
  { female: "Rauv", male: "Welv", meaning: "Cave, rock, stone" },
  { female: "Ril", male: "Ryl", meaning: "Foretold, omen" },
  { female: "Sbat", male: "Szor", meaning: "Amber, yellow" },
  { female: "Sab", male: "Tsab", meaning: "Abyss, empty, void" },
  { female: "Shi'n", male: "Kren", meaning: "Fool, foolish, young" },
  { female: "Shri", male: "Ssz", meaning: "Silk, silent" },
  { female: "Shur", male: "Shar", meaning: "Dagger, edge, stiletto" },
  { female: "Shynt", male: "", meaning: "Invisible, skilled, unseen" },
  { female: "Sin", male: "Szin", meaning: "Festival, joy, pleasure" },
  { female: "Ssap", male: "Tath", meaning: "Blue, midnight, nigh" },
  { female: "Susp", male: "Spir", meaning: "Learned, skilled, wise" },
  { female: "Talab", male: "Tluth", meaning: "Burn, burning, fire" },
  { female: "Tal", male: "Tar", meaning: "Love, pain, wound, wounded" },
  { female: "Triel", male: "Taz", meaning: "Bat, winged" },
  { female: "T'riss", male: "Teb", meaning: "Blade, sharp, sword" },
  { female: "Ulvir", male: "Uhls", meaning: "Gold, golden, treasure" },
  { female: "Umrae", male: "Hurz", meaning: "Faith, faithful, true" },
  { female: "Vas", male: "Vesz", meaning: "Blood, body, flesh" },
  { female: "Vic", male: "", meaning: "Abyss, deep, profound" },
  { female: "Vier", male: "Val", meaning: "Black, dark, darkness" },
  { female: "Vlon", male: "Wod", meaning: "Bold, hero, heroic" },
  { female: "Waer", male: "Wehl", meaning: "Deep, hidden, south, southern" },
  { female: "Wuyon", male: "Wruz", meaning: "Humble, third, trivial" },
  { female: "Xull", male: "Url", meaning: "Blooded, crimson, ruby" },
  { female: "Xun", male: "", meaning: "Demon, fiend, fiendish" },
  { female: "Yas", male: "Yaz", meaning: "Riddle, spinning, thread, web" },
  { female: "Zar", male: "Zakn", meaning: "Dusk, haunted, shadow" },
  { female: "Zebey", male: "Zek", meaning: "Dragon, lithe, rage, wyrm" },
  { female: "Zes", male: "Zsz", meaning: "Ancient, elder, respected" },
  { female: "Zilv", male: "Vuz", meaning: "Forgotten, old, unknown" }
];

export const firstSuff = [
  { female: "a", male: "agh", meaning: "Breaker, destruction, end, omega" },
  { female: "ace", male: "as", meaning: "Savant, scholar, wizard" },
  { female: "ae", male: "aun", meaning: "Dance, dancer, life, player" },
  { female: "aer", male: "d", meaning: "Blood, blood of, heir" },
  { female: "afae", male: "afein", meaning: "Bane, executioner, slayer" },
  { female: "afay", male: "aufein", meaning: "Eyes, eyes of, seeress/seer" },
  { female: "ala", male: "launim", meaning: "Healer, priestess/priest" },
  { female: "anna", male: "erin", meaning: "Advisor, counselor to" },
  { female: "arra", male: "atar", meaning: "Queen/prince, queen of/prince of" },
  { female: "aste", male: "", meaning: "Bearer, keeper, slaver" },
  { female: "avin", male: "aonar", meaning: "Guardian, guard, shield" },
  { female: "ayne", male: "al", meaning: "Lunatic, maniac, manic, rage" },
  { female: "baste", male: "gloth", meaning: "Path, walker" },
  { female: "breena", male: "antar", meaning: "Matriarch/patriarch, ruler" },
  { female: "bryn", male: "lyn", meaning: "Agent, assassin, killer" },
  { female: "cice", male: "roos", meaning: "Born of, child, young" },
  { female: "cyrl", male: "axle", meaning: "Ally, companion, friend" },
  { female: "da", male: "daer", meaning: "Illusionist, trickster" },
  { female: "dia", male: "drin", meaning: "Rogue, stealer" },
  { female: "diira", male: "diirn", meaning: "Initiate, sister/brother" },
  { female: "dra", male: "zar", meaning: "Lover, match, mate" },
  { female: "driira", male: "driirn", meaning: "Mother/father, teacher" },
  { female: "dril", male: "dorl", meaning: "Knight, sword, warrior" },
  { female: "e", male: "", meaning: "Servant, slave, vassal" },
  { female: "eari", male: "erd", meaning: "Giver, god, patron" },
  { female: "eyl", male: "", meaning: "Archer, arrow, flight, flyer" },
  { female: "ffyn", male: "fein", meaning: "Minstrel, singer, song" },
  { female: "fryn", male: "", meaning: "Champion, victor, weapon, weapon of" },
  { female: "iara", male: "ica", meaning: "Baron, duke, lady/lord" },
  { female: "ice", male: "eth", meaning: "Obsession, taker, taken" },
  {
    female: "idil",
    male: "imar",
    meaning: "Alpha, beginning, creator of, maker"
  },
  { female: "iira", male: "inid", meaning: "Harbinger, herald" },
  { female: "inidia", male: "", meaning: "Secret, wall, warder" },
  { female: "inil", male: "in", meaning: "Lady/lord, rider, steed" },
  { female: "intra", male: "", meaning: "Envoy, messenger, prophet" },
  { female: "isstra", male: "atlab", meaning: "Acolyte, apprentice, student" },
  { female: "ithra", male: "irahc", meaning: "Dragon, serpent, wyrm" },
  { female: "jra", male: "gos", meaning: "Beast, biter, stinger" },
  { female: "jss", male: "", meaning: "Scout, stalker" },
  { female: "kacha", male: "kah", meaning: "Beauty, hair, style" },
  { female: "kiira", male: "raen", meaning: "Apostle, disciple" },
  { female: "lay", male: "dyn", meaning: "Flight, flyer, wing, wings" },
  { female: "lara", male: "aghar", meaning: "Cynic, death, end, victim" },
  { female: "lin", male: "", meaning: "Arm, armor, commander" },
  { female: "lochar", male: "", meaning: "Messenger, spider" },
  { female: "mice", male: "myr", meaning: "Bone, bones, necromancer, witch" },
  { female: "mur'ss", male: "", meaning: "Shadow, spy, witness" },
  { female: "na", male: "nar", meaning: "Adept, ghost, spirit" },
  { female: "nilee", male: "olil", meaning: "Corpse, disease, ravager" },
  { female: "niss", male: "nozz", meaning: "Chance, gambler, game" },
  { female: "nitra", male: "net", meaning: "Kicker, returned, risen" },
  { female: "nolu", male: "", meaning: "Art, artist, expert, treasure" },
  { female: "olin", male: "", meaning: "Ascension, love, lover, lust" },
  { female: "onia", male: "onim", meaning: "Rod, staff, token, wand" },
  { female: "oyss", male: "omph", meaning: "Binder, judge, law, prison" },
  { female: "qualyn", male: "", meaning: "Ally, caller, kin" },
  { female: "quarra", male: "net", meaning: "Horde, host, legion" },
  { female: "quiri", male: "oj", meaning: "Aura, cloak, hide, skin" },
  { female: "ra", male: "or", meaning: "Fool, game, prey, quarry" },
  { female: "rae", male: "rar", meaning: "Secret, seeker, quest" },
  { female: "raema", male: "orvir", meaning: "Crafter, fist, hand" },
  { female: "raena", male: "olvir", meaning: "Center, haven, home" },
  { female: "riia", male: "rak", meaning: "Chaos, storm, tempest" },
  { female: "ril", male: "", meaning: "Bandit, enemy, raider, outlaw" },
  { female: "riina", male: "ree", meaning: "Enchanter, mage, spellcaster" },
  { female: "ryna", male: "oyn", meaning: "Follower, hired, mercenary" },
  { female: "ryne", male: "ryn", meaning: "Blooded, elder, experienced" },
  { female: "shalee", male: "ral", meaning: "Abjurer, gaze, watch, watcher" },
  {
    female: "ssysn",
    male: "rysn",
    meaning: "Artifact, dweomer, sorcerer, spell"
  },
  {
    female: "stin",
    male: "trin",
    meaning: "Clan, house, merchant, of the house"
  },
  { female: "stra", male: "tran", meaning: "Spider, spinner, weaver" },
  { female: "tana", male: "ton", meaning: "Darkness, lurker, prowler" },
  { female: "thara", male: "tar", meaning: "Glyph, marker, rune" },
  { female: "thrae", male: "olg", meaning: "Charmer, leader, seducer" },
  { female: "tree", male: "tel", meaning: "Exile, loner, outcast, pariah" },
  { female: "tyrr", male: "", meaning: "Dagger, poison, poisoner, scorpion" },
  { female: "ual", male: "dan", meaning: "Speed, strider" },
  { female: "ue", male: "dor", meaning: "Arm, artisan, fingers" },
  { female: "uit", male: "dar", meaning: "Breath, voice, word" },
  { female: "une", male: "diin", meaning: "Diviner, fate, future, oracle" },
  { female: "uque", male: "", meaning: "Cavern, digger, mole, tunnel" },
  { female: "urra", male: "dax", meaning: "Nomad, renegade, wanderer" },
  { female: "va", male: "ven", meaning: "Comrade, honor, honored" },
  { female: "vayas", male: "", meaning: "Forge, forger, hammer, smith" },
  { female: "vyll", male: "", meaning: "Punishment, scourge, whip, zealot" },
  { female: "vyrae", male: "vyr", meaning: "Mistress/master, overseer" },
  { female: "wae", male: "hrae", meaning: "Heir, inheritor, princess" },
  { female: "wiira", male: "hriir", meaning: "Seneschal of, steward" },
  { female: "wyss", male: "hrys", meaning: "Best, creator, starter" },
  { female: "xae", male: "zaer", meaning: "Orb, rank, ruler, scepter" },
  { female: "xena", male: "zen", meaning: "Cutter, gem, jewel, jeweler" },
  { female: "xyra", male: "zyr", meaning: "Sage, teller" },
  { female: "yl", male: "", meaning: "Drow, woman/man" },
  { female: "ylene", male: "yln", meaning: "Handmaiden/squire, maiden/youth" },
  { female: "ymma", male: "inyon", meaning: "Drider, feet, foot, runner" },
  {
    female: "ynda",
    male: "yrd",
    meaning: "Captain, custodian, marshal, ranger"
  },
  { female: "ynrae", male: "yraen", meaning: "Heretic, rebel, riot, void" },
  { female: "yrae", male: "", meaning: "Architect, founder, mason" },
  { female: "yrr", male: "", meaning: "Protector, rival, wielder" },
  { female: "zyne", male: "zt", meaning: "Finder, hunter" }
];

export const housePre = [
  { name: "Alean", meaning: "The noble line of" },
  { name: "Ale", meaning: "Traders in" },
  { name: "Arab", meaning: "Daughters of" },
  { name: "Arken", meaning: "Mages of" },
  { name: "Auvry", meaning: "Blood of the" },
  { name: "Baen", meaning: "Blessed by" },
  { name: "Barri", meaning: "Spawn of" },
  { name: "Cladd", meaning: "Warriors from" },
  { name: "Desp", meaning: "Victors of" },
  { name: "De", meaning: "Champions of" },
  { name: "Do'", meaning: "Walkers in" },
  { name: "Eils", meaning: "Lands of" },
  { name: "Everh", meaning: "The caverns of" },
  { name: "Fre", meaning: "Friends to" },
  { name: "Gode", meaning: "Clan of" },
  { name: "Helvi", meaning: "Those above" },
  { name: "Hla", meaning: "Seers of" },
  { name: "Hun'", meaning: "The sisterhood of" },
  { name: "Ken", meaning: "Sworn to" },
  { name: "Kil", meaning: "People of" },
  { name: "Mae", meaning: "Raiders from" },
  { name: "Mel", meaning: "Mothers of" },
  { name: "My", meaning: "Honored of" },
  { name: "Noqu", meaning: "Sacred to" },
  { name: "Orly", meaning: "Guild of" },
  { name: "Ouss", meaning: "Heirs to" },
  { name: "Rilyn", meaning: "House of" },
  { name: "Teken'", meaning: "Delvers in" },
  { name: "Tor", meaning: "Mistresses of" },
  { name: "Zau", meaning: "Children of" }
];

export const houseSuff = [
  { name: "afin", meaning: "The web" },
  { name: "ana", meaning: "The night" },
  { name: "ani", meaning: "The widow" },
  { name: "ar", meaning: "Poison" },
  { name: "arn", meaning: "Fire" },
  { name: "ate", meaning: "The way" },
  { name: "ath", meaning: "The dragons" },
  { name: "duis", meaning: "The whip" },
  { name: "ervs", meaning: "The depths" },
  { name: "ep", meaning: "The Underdark" },
  { name: "ett", meaning: "Magic" },
  { name: "ghym", meaning: "The forgotten ways" },
  { name: "iryn", meaning: "History" },
  { name: "lyl", meaning: "The blade" },
  { name: "mtor", meaning: "The abyss" },
  { name: "ndar", meaning: "Black hearts" },
  { name: "neld", meaning: "The arcane" },
  { name: "rae", meaning: "Fell powers" },
  { name: "rahel", meaning: "The gods" },
  { name: "rret", meaning: "The void" },
  { name: "sek", meaning: "Adamantite" },
  { name: "th", meaning: "Challenges" },
  { name: "tlar", meaning: "Mysteries" },
  { name: "t'tar", meaning: "Victory" },
  { name: "tyl", meaning: "The pits" },
  { name: "und", meaning: "The spider's kiss" },
  { name: "urden", meaning: "The darkness" },
  { name: "val", meaning: "Silken weaver" },
  { name: "viir", meaning: "Dominance" },
  { name: "zynge", meaning: "The ruins" }
];
